#############################################################################
- id: salon1
  alias: IM salon (CDL) -> amp. salon moyenne
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_livingroom_both
      click_type: long_both
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalon
    data:
      brightness: 150
      kelvin: 4000
#############################################################################
- id: salon2
  alias: IM salon (gauche) -> amp. salon forte
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_livingroom_left
      click_type: single
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalon
    data:
      brightness: 255
      kelvin: 5000
#############################################################################
- id: salon3
  alias: IM salon (droit) -> amp. salon faible
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_livingroom_right
      click_type: single
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalon
    data:
      brightness: 100
      kelvin: 3000
#############################################################################
- id: salon4
  alias: IM salon (CSim) -> amp. salon off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_livingroom_both
      click_type: both
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.AmpouleSalon
#############################################################################
- id: salon5
  alias: IP salon (CS) -> amp. salon on /off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.portable_livingroom
      click_type: single
  condition: []
  action:
  - service: light.toggle
    entity_id: light.AmpouleSalon
#############################################################################
- id: salon6
  alias: IP salon (CL) -> amp. salon faible
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.portable_livingroom
      click_type: long_click_press
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalon
    data_template:
      brightness: 100
      kelvin: 2500
#############################################################################
- id: salon7
  alias: IP salon (CD) -> amp. salon forte
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.portable_livingroom
      click_type: double
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalon
    data:
      brightness: 255
      kelvin: 5000
#############################################################################
- id: salon8
  alias: TV éteinte & lumières éteintes -> gateway 2 min
  trigger:
#    platform: state
#    entity_id: media_player.lg_oled55b7
#    from: 'playing'
#    to: 'off'
    platform: template
    value_template: '{{ states.media_player.lg_oled55b7.attributes.entity_picture == null }}'
  condition:
  - condition: state
    entity_id: group.all_lights
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.illumination_gateway
    below: 80
  action:
  - service: light.turn_on
    entity_id: light.ledGateway
    data:
      rgb_color: [255, 120, 19]
      brightness: 255
  - delay: 00:02:00
  - service: light.turn_off
    entity_id: light.ledGateway 
#############################################################################
- id: cuisine1
  alias: IM cuisine (CDL) -> amp. cuisine moyenne
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_kitchen_both
      click_type: long_both
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleCuisine
    data:
      brightness: 150
      kelvin: 4000
#############################################################################
- id: cuisine2
  alias: IM cuisine (gauche) -> amp. cuisine fort
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_kitchen_left
      click_type: single
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleCuisine
    data:
      brightness: 255
      kelvin: 5000
#############################################################################
- id: cuisine3
  alias: IM cuisine (droit) -> amp. cuisine faible
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_kitchen_right
      click_type: single
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleCuisine
    data:
      brightness: 100
      kelvin: 3000
#############################################################################
- id: cuisine4
  alias: IM cuisine (CSim) -> amp. cuisine off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_kitchen_both
      click_type: both
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.AmpouleCuisine
#############################################################################
- id: chambre1
  alias: IM chambre (CS) et amp. chambre off -> Chambre on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bedroom
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleChambre
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.turn_on_bedroom
#############################################################################
- id: chambre2
  alias: IM chambre (CL) et amp. chambre off -> Chambre on inverse
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bedroom
      click_type: long
  condition:
  - condition: state
    entity_id: light.AmpouleChambre
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.turn_on_bedroom_reverse
#############################################################################
- id: chambre3
  alias: IM chambre (CS) et amp. chambre on -> Chambre off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bedroom
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleChambre
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.turn_off_bedroom
#############################################################################
- id: chambre4
  alias: IP chambre (CS) et amp. chambre off -> Chambre on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.portable_bedroom
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleChambre
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.turn_on_bedroom
#############################################################################
- id: chambre5
  alias: IP chambre (CL) et amp. chambre off -> Chambre on inverse
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.portable_bedroom
      click_type: hold
  condition: []
  action:
    service: script.turn_on
    entity_id: script.turn_on_bedroom_reverse
#############################################################################
- id: chambre6
  alias: IP chambre (CS) et amp. chambre on -> Chambre off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.portable_bedroom
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleChambre
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.turn_off_bedroom
#############################################################################
- id: couloir1
  alias: Détecteur mouv. couloir on -> amp. couloir on
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_hall
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleCouloir
    data_template:
      brightness: >
        {% if now().hour >= 22 %}
          25
        {% elif now().hour < 9 %}
          15
        {% else %}
          180
        {% endif %}
      kelvin: >
        {% if now().hour >= 22 %}
          3000
        {% elif now().hour < 9 %}
          2500
        {% else %}
          4500
        {% endif %}
#############################################################################
- id: couloir2
  alias: Détecteur mouv. couloir off -> amp. couloir off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_hall
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.AmpouleCouloir
#############################################################################
- id: couloir3
  alias: IM salon (CDDroit) ET couloir off -> amp. couloir on ET autom. couloir off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_livingroom_right
      click_type: double
  # condition:
  # - condition: state
    # entity_id: light.AmpouleCouloir
    # state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.AmpouleCouloir
  - service: automation.turn_off
    entity_id: automation.detecteur_mouv_couloir_off_ampoule_couloir_off
#############################################################################
- id: couloir4
  alias: IM salon (CDDroit) ET couloir on -> amp. couloir off ET autom. couloir on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_livingroom_right
      click_type: double
  condition:
  - condition: state
    entity_id: light.AmpouleCouloir
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.AmpouleCouloir
  - service: automation.turn_on
    entity_id: automation.detecteur_mouv_couloir_off_ampoule_couloir_off
#############################################################################
- id: routine1
  alias: Routine réveil
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
  - condition: template
    value_template: >
      {{ as_timestamp(now()) | timestamp_custom("%d%m%Y%H%M") == states.input_datetime.morning_routine_date_time.attributes.timestamp | timestamp_custom("%d%m%Y%H%M")}}
  action:
  - service: light.turn_on
    entity_id: light.AmpouleChambre
    data:
      rgb_color: [255, 0, 0]
      brightness_pct: 1
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.AmpouleChambre
    data:
      rgb_color: [255,100,0]
      brightness_pct: 1
      transition: 420
  - delay: 00:07:00
  - service: light.turn_on
    entity_id: light.AmpouleChambre
    data:
      rgb_color: [255,230,200]
      brightness_pct: 1
      transition: 240
  - delay: 00:04:00
  - service: light.turn_on
    entity_id: light.AmpouleChambre
    data:
      rgb_color: [255,230,200]
      brightness_pct: 30
      transition: 180
  - delay: 00:00:05
  - wait_template: >
      {{ is_state('binary_sensor.motion_sensor_hall', 'on') }}
  - delay: 00:00:01
  - service: light.turn_on
    entity_id: light.AmpouleToilettes
    data:
      brightness: 20
      kelvin: 3000
  - delay: 00:00:01
  - service: light.turn_on
    entity_id: light.AmpouleSalleDeBain
    data:
      brightness: 20
      kelvin: 3000
  - delay: 00:00:01
  - service: light.turn_on
    entity_id: light.AmpouleSalon
    data:
      brightness: 255
      kelvin: 5000
  - service: light.turn_on
    entity_id: light.AmpouleCuisine
    data:
      brightness: 255
      kelvin: 5000
# --------------------------------------
# calculer l'écart en minutes entre l'heure actuelle et l'heure de départ au travail paramétrée. 
# Si ce temps est suffisamment faible, on est dans le cas d'un jour de travail et l'on continue sur la routine.
# --------------------------------------
  - condition: template
    value_template: >
      {% set departure_time_minutes = (states.input_datetime.home_departure_time.attributes.timestamp | timestamp_custom("%H", false) | int * 60 
        + states.input_datetime.home_departure_time.attributes.timestamp | timestamp_custom("%M", false) | int ) %}
      {% set now_minutes = (as_timestamp(now()) | timestamp_custom("%H") | int * 60 + (as_timestamp(now()) | timestamp_custom("%M") | int)) %}
      {{ departure_time_minutes - now_minutes < 60 and departure_time_minutes - now_minutes > 0 }}
# --------------------------------------
# attendre l'heure de départ au travail moins 4 minutes
# --------------------------------------
  - wait_template: >
      {% set four_minutes_before_departure_time = states.input_datetime.home_departure_time.attributes.timestamp | int -(4*60) %}
      {% set time_now = as_timestamp(strptime(states.sensor.date_time.state, '%Y-%m-%d, %H:%M'))| timestamp_custom("%H%M") %}
      {{ time_now  == four_minutes_before_departure_time | timestamp_custom("%H%M", false)}}
  - service: light.turn_on
    entity_id: light.ledGateway
    data:
      rgb_color: [255, 127, 0]
      brightness_pct: 60
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.ledGateway
    data:
      rgb_color: [255, 84, 0]
      brightness_pct: 75
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.ledGateway
    data:
      rgb_color: [255, 42, 0]
      brightness_pct: 90
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.ledGateway
    data:
      rgb_color: [255, 0, 0]
      brightness_pct: 100
  - delay: 00:06:00
  - service: light.turn_off
    entity_id: group.all_lights
#############################################################################
- id: bathroom1
  alias: IM sdb (CS) et amp. sdb off -> sdb on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bathroom
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleSalleDeBain
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.turn_on_bathroom
#############################################################################
- id: bathroom2
  alias: IM sdb (CL) -> sdb faible
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bathroom
      click_type: long
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalleDeBain
    data:
      brightness: 80
      kelvin: 3000
#############################################################################
- id: bathroom3
  alias: IM sdb (CD) -> sdb max
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bathroom
      click_type: double
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleSalleDeBain
    data:
      brightness: 255
      kelvin: 4500
#############################################################################
- id: bathroom4
  alias: IM sdb (CS) et amp. sdb on -> sdb off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_bathroom
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleSalleDeBain
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.AmpouleSalleDeBain
#############################################################################
- id: toilets1
  alias: IM toilettes (CS) et amp. toilettes off -> toilettes on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_toilets
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleToilettes
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.turn_on_toilets
#############################################################################
- id: toilets2
  alias: IM toilettes (CL) -> toilettes faible
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_toilets
      click_type: long
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleToilettes
    data:
      brightness: 80
      kelvin: 3000
#############################################################################
- id: toilets3
  alias: IM toilettes (CD) -> toilettes max
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_toilets
      click_type: double
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.AmpouleToilettes
    data:
      brightness: 255
      kelvin: 4500
#############################################################################
- id: toilets4
  alias: IM toilettes (CS) et amp. toilettes on -> toilettes off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_toilets
      click_type: single
  condition:
  - condition: state
    entity_id: light.AmpouleToilettes
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.AmpouleToilettes
