homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.2144
  longitude: -1.5512
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/Recordings
    - /tmp

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: ./ssl/fullchain.pem
  ssl_key: ./ssl/privkey.pem
  base_url: tranquility-base.duckdns.org:8123

# Discover some devices automatically
discovery:
  ignore:
    - yeelight
    - apple_tv
    - belkin_wemo
    - bluesound
    - bose_soundtouch
    - plex_mediaserver

script: !include scripts.yaml
group: !include groups.yaml
automation: !include automations.yaml

yeelight:
  devices:
    192.168.0.21:
      name: AmpouleToilettes
    192.168.0.20:
      name: AmpouleSalon
    192.168.0.27:
      name: AmpouleBureau
    192.168.0.28:
      name: AmpouleChambre
    192.168.0.29:
      name: LampeChevet
    192.168.0.23:
      name: AmpouleSalleDeBain
    192.168.0.24:
      name: AmpouleCuisine
    192.168.0.25:
      name: AmpouleCouloir

light:
  - platform: group
    name: Lumière Salon
    entities:
      - light.AmpouleSalon
      - light.AmpouleBureau

sensor:
  - platform: command_line
    name: Température CPU
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  # - platform: command_line
    # entity_id: isControllerConnected
    # friendly_name: Mannette connectée
    # command:  xboxdrv -L | wc -l
    # value_template: '{{ value | int > 2 }}'
  # Weather prediction
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - symbol
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: last_boot
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

input_datetime:
  morning_routine_date_time:
    name: Heure du réveil-matin
    has_date: true
    has_time: true
  home_departure_time:
    name: Heure de départ de la maison
    has_date: false
    has_time: true

input_number:
  battery_charging_percentage_limit_antoine:
    name: Limite charge smartphone Antoine
    initial: 80
    min: 0
    max: 100
    step: 1
    mode: box
  battery_charging_percentage_limit_anh:
    name: Limite charge smartphone Anh
    initial: 80
    min: 0
    max: 100
    step: 1
    mode: box
  speakers_turnoff_timer:
    name: Délai extinction enceintes
    unit_of_measurement: "minutes"
    initial: 45
    min: 0
    max: 240
    step: 5
    mode: slider

# You can leave MAC empty if you only have one gateway.
xiaomi_aqara:
  discovery_retry: 15
  gateways:
    - key: !secret gatewayKey

wake_on_lan:

media_player:
  - platform: webostv
    name: LG_OLED55B7
    host: 192.168.0.26
    timeout: 4
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "20:3D:BD:01:7B:0A"
  - platform: plex

notify:
  - platform: webostv
    host: 192.168.0.26
    name: LG_OLED55B7
  - platform: html5
    name: Antoine_notification
    vapid_pub_key: BBw5KDowbSWcJSLhISTIOxaXnu6SQHeCPaUiRza8fiy9GJeXIhC_kS9HUHIFINsDmH_9Qr79tHuuzku5pOPYBlQ
    vapid_prv_key: JRtMffWLI9mBlKS-Qr7Sc549fhYwuO2O0xXo63YbBXY
    vapid_email: jouet.antoine@gmail.com
  - name: antoine_anh_tv
    platform: group
    services:
      - service: antoine_notification
      - service: lg_oled55b7

google_assistant:
  project_id: assistantautomationintegration
  api_key: !secret googleCloudApiKey
  exposed_domains:
    - light
    - media_player
    - switch
  entity_config:
    media_player.lg_oled55b7:
      expose: true
    script.sunset_bedroom:
      expose: true
    group.all_automations:
      expose: false


device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 15
    exclude:
      - 192.168.0.44

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    input: !secret cameraStream

stream:

binary_sensor:
  - platform: ffmpeg_motion
    name: camera_motion
    input: !secret cameraStream
    changes: 8



