homeassistant:
  # Name of the location where Home Assistant is running
#  name: Home
  # Location required to calculate the time the sun rises and sets
#  latitude: 47.2144
#  longitude: -1.5512
  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: 0
  # metric for Metric, imperial for Imperial
#  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/Recordings
    - /config/ssl
    - /config/sh

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /etc/letsencrypt/live/tranquility-base.eu/fullchain.pem
  ssl_key: /etc/letsencrypt/live/tranquility-base.eu/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies: 
   - 127.0.0.1
   - 192.168.0.101

script: !include scripts.yaml
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

recorder:
  # db_url: postgresql://hass:mvtmjsun42@127.0.0.1/hass
  db_url: postgresql://hass:mvtmjsun42@192.168.0.101:5433/hass
  commit_interval: 5

xiaomi_aqara:
  discovery_retry: 15
  gateways:
    - key: !secret gatewayKey

#zha_map:

yeelight:
  devices:
#     192.168.0.120:
#       name: AmpouleSalleDeBain
    192.168.0.121:
      name: AmpouleBureau
#     192.168.0.122:
#       name: AmpouleToilettes
#     192.168.0.123:
#       name: AmpouleSalon
#     192.168.0.124:
#       name: AmpouleCouloir
#     192.168.0.125:
#       name: AmpouleCuisine
#     192.168.0.126:
#       name: AmpouleChambre
#     192.168.0.127:
#       name: LampeChevet

light:
  - platform: group
    name: Lumière Salon
    entities:
      - light.AmpouleSalon
      - light.AmpouleBureau
      - light.livingroom_led_strip
  - platform: group
    name: Lumière Chambre
    entities:
      - light.AmpouleChambre
      - light.LampeChevet
  - platform: group
    name: Lumière Miroir Salle de Bain
    entities: 
      - light.bathroom_bulb_1_cwww
      - light.bathroom_bulb_2_cwww
  - platform: group
    name: Lumière Miroir Salle de Bain RGB
    entities: 
      - light.bathroom_bulb_1_rgb
      - light.bathroom_bulb_2_rgb

sensor:
  # - platform: file
  #   name: Activité hdd
  #   file_path: /config/sh/hddspinsensor.txt
  - platform: command_line
    name: Température CPU
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
#    - type: disk_use_percent
#      arg: /mnt/hdd
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
  - platform: integration
    source: sensor.tv_power_usage
    name: tv_energy_spent
    unit_prefix: k
    method: left
    round: 2
  - platform: integration
    source: sensor.m365_power_usage
    name: m365_energy_spent
    unit_prefix: k
    method: left
    round: 2
  - platform: integration
    source: sensor.livingroom_multimedia_power_usage
    name: livingroom_multimedia_energy_spent
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.heating_blanket_power_usage
    name: heating_blanket_energy_spent
    unit_prefix: k
    method: left
    round: 2
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: derivative
    source: sensor.battery_level_antoine
    round: 1
    unit: "%/h"
    time_window: "00:15:00"
  - platform: template
    sensors:
      battery_derivative_positive_antoine:
        friendly_name: "Charge batterie Antoine"
        unit_of_measurement: '%/h'
        value_template: >
          {% if states.sensor.sensor_battery_level_antoine_derivative.state | float > 0 %}
            {{ states.sensor.sensor_battery_level_antoine_derivative.state | float }}
          {% else %}
            0
          {% endif %}
      battery_derivative_negative_antoine:
        friendly_name: "Décharge batterie Antoine"
        unit_of_measurement: '%/h'
        value_template: >
          {% if states.sensor.sensor_battery_level_antoine_derivative.state | float < 0 %}
            {{ states.sensor.sensor_battery_level_antoine_derivative.state | float }}
          {% else %}
            0
          {% endif %}
      weather_nantes_temperature:
        friendly_name: "Température Nantes"
        unit_of_measurement: '°C'
        value_template: >
          {{ state_attr('weather.nantes', 'temperature') }}
  - platform: derivative
    source: sensor.battery_level_anh
    round: 1
    unit: "%/h"
    time_window: "00:15:00"
  - platform: template
    sensors:
      battery_derivative_positive_anh:
        friendly_name: "Charge batterie Anh"
        unit_of_measurement: '%/h'
        value_template: >
          {% if states.sensor.sensor_battery_level_anh_derivative.state | float > 0 %}
            {{ states.sensor.sensor_battery_level_anh_derivative.state | float }}
          {% else %}
            0
          {% endif %}
      battery_derivative_negative_anh:
        friendly_name: "Décharge batterie Anh"
        unit_of_measurement: '%/h'
        value_template: >
          {% if states.sensor.sensor_battery_level_anh_derivative.state | float < 0 %}
            {{ states.sensor.sensor_battery_level_anh_derivative.state | float }}
          {% else %}
            0
          {% endif %}
  - platform: statistics
    name: battery_derivative_negative_antoine_statistics
    entity_id: sensor.battery_derivative_negative_antoine
    sampling_size: 4
    max_age:
      minutes: 90
  - platform: rest
    resource: http://192.168.0.101:61208/api/3/network/interface_name/enp1s0
    name: network_powerhouse
    headers:
      Accept-Encoding: ''
    value_template: 'interface: enp1s0'
    json_attributes_path: "$.enp1s0.[0]"
    json_attributes: 
      - tx
      - rx
    scan_interval: 45
  - platform: rest
    resource: https://mabbox.bytel.fr/api/v1/wan/ip/stats
    name: bbox_network_rx
    headers:
      Accept-Encoding: ''
    value_template: 'interface: bbox'
    json_attributes_path: "$.[0].wan.ip.stats.rx"
    json_attributes: 
      - occupation
      - bytes
    scan_interval: 12
  - platform: rest
    resource: https://mabbox.bytel.fr/api/v1/wan/ip/stats
    name: bbox_network_tx
    headers:
      Accept-Encoding: ''
    value_template: 'interface: bbox'
    json_attributes_path: "$.[0].wan.ip.stats.tx"
    json_attributes: 
      - occupation
      - bytes
    scan_interval: 12
  # - platform: rest
  #   resource: https://mabbox.bytel.fr/api/v1/wan/ip/stats
  #   sensor: 
  #     - name: bbox_network_rx
  #       value_template: 'bbox network'    
  #       json_attributes_path: "$.[0].wan.ip.stats.rx"
  #       json_attributes: 
  #         - occupation
  #         - bytes
  #       scan_interval: 12
  #     - name: bbox_network_tx
  #       value_template: 'bbox network'    
  #       json_attributes_path: "$.[0].wan.ip.stats.tx"
  #       json_attributes: 
  #         - occupation
  #         - bytes
  #       scan_interval: 12
  - platform: template
    sensors:
      download_powerhouse:
        value_template: '{{ states.sensor.network_powerhouse.attributes["rx"] | multiply(0.000000954/8) | multiply(0.16666) | round(2) }}'
        unit_of_measurement: Mo/s
      upload_powerhouse:
        value_template: '{{ states.sensor.network_powerhouse.attributes["tx"] | multiply(0.000000954/8) | multiply(0.16666) | round(2) }}'
        unit_of_measurement: Mo/s
      download_bbox:
        value_template: >
          {% set rxSpeed = states.sensor.bbox_network_rx.attributes["occupation"] | multiply(0.125) | round(2) %}
          {% if rxSpeed != 125 %}
            {{ rxSpeed }}
          {% else %}
            {{ 0 }}
          {% endif %}
        unit_of_measurement: Mo/s
      total_download_bbox:
        value_template: '{{ states.sensor.bbox_network_rx.attributes["bytes"] | multiply(0.000000954) | round(2) }}'
        unit_of_measurement: Mo
      upload_bbox:
        value_template: >
          {% set rxSpeed = states.sensor.bbox_network_tx.attributes["occupation"] | multiply(0.125) | round(2) %}
          {% if rxSpeed != 125 %}
            {{ rxSpeed }}
          {% else %}
            {{ 0 }}
          {% endif %}
        unit_of_measurement: Mo/s
      total_upload_bbox:
        value_template: '{{ states.sensor.bbox_network_tx.attributes["bytes"] | multiply(0.000001) | round(2) }}'
        unit_of_measurement: Mo
  - platform: history_stats
    name: time_on_smartphone_screen_antoine
    entity_id: input_boolean.smartphone_screen_antoine
    state: "on"
    type: time
    start: "{{ now().replace(hour=4, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: time_on_smartphone_screen_anh
    entity_id: input_boolean.smartphone_screen_anh
    state: "on"
    type: time
    start: "{{ now().replace(hour=4, minute=0, second=0) }}"
    end: "{{ now() }}"      

utility_meter:
  monthly_tv_power_usage:
    source: sensor.tv_energy_spent
    cycle: monthly
  monthly_multimedia_power_usage:
    source: sensor.livingroom_multimedia_energy_spent
    cycle: monthly
  monthly_m365_power_usage:
    source: sensor.m365_energy_spent
    cycle: monthly
  monthly_heating_blanket_power_usage:
    source: sensor.heating_blanket_energy_spent
    cycle: monthly
  monthly_total_download_bbox:
    source: sensor.total_download_bbox
    cycle: monthly
  monthly_total_upload_bbox:
    source: sensor.total_upload_bbox
    cycle: monthly

input_datetime:
  morning_routine_date_time:
    name: Heure du réveil-matin
    has_date: true
    has_time: true
  home_departure_time:
    name: Heure de départ de la maison
    has_date: false
    has_time: true

input_number:
  battery_charging_percentage_limit_antoine:
    name: Limite charge smartphone Antoine
    unit_of_measurement: "%"
    initial: 80
    min: 0
    max: 100
    step: 1
    mode: box
  battery_charging_percentage_limit_anh:
    name: Limite charge smartphone Anh
    unit_of_measurement: "%"
    initial: 80
    min: 0
    max: 100
    step: 1
    mode: box
  speakers_turnoff_timer:
    name: Délai extinction enceintes
    unit_of_measurement: "minutes"
    initial: 60
    min: 0
    max: 240
    step: 5
    mode: slider
  speakers_target_volume:
    name: Vol. cible
    unit_of_measurement: "%"
    initial: 3
    min: 0
    max: 100
    step: 1
    mode: slider
  speakers_volume_change_duration:
    name: Durée transition
    unit_of_measurement: "minutes"
    initial: 5
    min: 0
    max: 120
    step: 1
    mode: box
# hidden
  speakers_start_volume:
    name: Volume initial des enceintes
    initial: 20
    min: 0
    max: 100
    step: 1
    mode: box
    
timer:
  m365_charge_timer:
    name: temps de charge restant
    duration: '01:10:00'

wake_on_lan:

webostv:
  host: 192.168.0.20
  name: LG_OLED55B7
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "20:3D:BD:01:7B:0A"

# media_player:
  # - platform: webostv
    # name: LG_OLED55B7
    # host: 192.168.0.26
    # timeout: 4
    # turn_on_action:
      # service: wake_on_lan.send_magic_packet
      # data:
        # mac: "20:3D:BD:01:7B:0A"
  # - platform: plex

notify:
  - platform: webostv
    host: 192.168.0.10
    name: LG_OLED55B7
  - platform: html5
    name: Antoine_notification
    vapid_pub_key: BPXPgvtb_hedm1UXjYk1zQi75CCQCEyeK5cE-HnM4WjR5FCB69q3i9ct9WYLfHJ9-Vw1EuAPqxTbmNQJKmxs4S8
    vapid_prv_key: D4BIhir6k0CFn_tkSmrRe2Yx6yY4DO3bCfkB07D58Gc
    vapid_email: jouet.antoine@gmail.com
  - name: antoine_anh_tv
    platform: group
    services:
      - service: antoine_notification
      - service: lg_oled55b7

# google_assistant:
  # project_id: assistantautomationintegration
  # api_key: !secret googleCloudApiKey
  # exposed_domains:
    # - light
    # - media_player
    # - switch
  # entity_config:
    # media_player.lg_oled55b7:
      # expose: true
    # script.sunset_bedroom:
      # expose: true
    # group.all_automations:
      # expose: false


device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.254/24
    home_interval: 15
#    consider_home: 0:03:00
    scan_options: "-F –host-timeout 15s"
    exclude:
      - 192.168.0.44

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    input: !secret cameraStream

stream:

binary_sensor:
  - platform: ffmpeg_motion
    name: camera_motion
    input: !secret cameraStream
    changes: 14
    extra_arguments: -vf scale=640:480
